apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
    service: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb
  selector:
    app: mariadb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: "mariadb-service"
  selector:
    matchLabels:
      app: mariadb
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: mariadb
        version: v1
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password123"
        - name: MYSQL_DATABASE
          value: "apan50demo"
        ports:
          - containerPort: 3306
            name: mariadb
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "2048Mi"
        volumeMounts:
          - name: mariadb-data
            mountPath: /var/lib/mysql
      volumes:
         - name: mariadb-data
            hostPath:
              path: /data
              type: Directory

---
