apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: python-client
  namespace: default
spec:
  selector:
    matchLabels:
      app: python-client
  template:
    metadata:
      labels:
        app: python-client
    spec:
      containers:
      - name: python-client
        image: alexnjh/apan50-python-client:0.0.2
        env:
        - name: SERVER_HOSTNAME
          value: "python-service.default.svc.cluster.local"
        - name: SERVER_PORT
          value: "5000"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "64Mi"
            cpu: "5m" #(0.25 of cpu)
          limits:
            memory: "128Mi"
            cpu: "5m" #(0.25 of cpu)
